version: '3'

services:
  database:
    container_name: 'doe'
    image: 'postgres:13-alpine'
    restart: always
    environment:
      POSTGRES_USER: DOE_APP
      POSTGRES_PASSWORD: Qwerty
      POSTGRES_DATABASE: DOE_APP
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5434:5432

volumes:
  pg-data:
