version: '3'

services:
  database:
    container_name: 'doe'
    image: 'postgres:13-alpine'
    environment:
      POSTGRES_USER: DOE_APP
      POSTGRES_PASSWORD: Qwerty
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5434:5432
